name: Haskell CI

on:
  push:
    branches: [ mawa ]
  pull_request:
    branches: [ mawa ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v2
      with:
        ghc-version: '9.2.6'
        cabal-version: '3.6.2.0'

    - name: Cache Cabal Store
      uses: actions/cache@v2
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal

    - name: Install librdkafka
      run: |
        sudo apt-get update
        sudo apt-get install -y librdkafka-dev

    - name: Install dependencies
      run: |
        cabal update
        cabal configure
        cabal build --only-dependencies --enable-tests --enable-benchmarks

    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all
